from __future__ import annotations

import numpy as np
import numpy.typing as npt

class FastTextParallelError(RuntimeError): ...
class ModelLoadError(FastTextParallelError): ...
class PredictionError(FastTextParallelError): ...
class InvalidInputError(FastTextParallelError): ...

class FastTextParallelModel:
    def __init__(self, model_path: str, threads: int) -> None: ...
    @property
    def threads(self) -> int: ...
    def predict_many(
        self,
        lines: list[str],
        k: int,
        threshold: float,
        on_unicode_error: str = "strict",
    ) -> tuple[list[list[str]], list[npt.NDArray[np.float32]]]: ...
